version: '3.8'

services:

  db:
    build: ./db
    container_name: app_db_container
    environment:
      POSTGRES_USER: app_database
      POSTGRES_PASSWORD: app_user
      POSTGRES_DB: user123
    volumes:
      - faq-postgres-data:/var/lib/postgresql/data
      - ./bd/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "2000:5432"
    networks:
      - app-network

  
  web:
  build: ./app
  ports:
    - "3000:3000"
  environment:
    - NODE_ENV=development
  volumes:
    - .:/usr/src/app
    - /usr/scr/app/node_modules
  command: npm run dev
  depends_on:
    - db
  networks:
    - app-network

networks:
  app-network:
    driver: bridge