#imagem do node
FROM node:22

#diretório de trabalho
WORKDIR /usr/src/app

#copia arquivo da aplicação
COPY package.json / 

#instala as dependências
RUN npm install

#copia o codigo do app
COPY ..  /

#expõe a porta
EXPOSE 3000

#comando de inicialização
CMD ["npm","start"]